(function(g){var window=this;var A3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.Bz(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},B3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},ita=function(a,b){var c=new g.Az;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},jta=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];
if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var k=a[c++],l=a[c++];e=((e&7)<<18|(f&63)<<12|(k&63)<<6|l&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],k=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|k&63)}return b.join("")},kta=function(){this.u=[];
this.o=[]},C3=function(a,b){return b?a.o.concat(a.u):a.o},D3=function(a,b){switch(b.kind){case "asr":var c=a.u;
g.Za(c,(0,g.x)(b.Qs,b))||c.push(b);break;default:c=a.o,g.Za(c,(0,g.x)(b.Qs,b))||c.push(b)}},E3=function(){g.A.call(this);
this.u=new kta;this.B=[]},F3=function(a,b,c){E3.call(this,a);
this.o=null;this.B=b.bw;this.w=c},G3=function(){this.segments=[]},lta=function(a,b){var c=g.qb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.eb(a.segments,c),g.eb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.nb(a.segments,c,0,b),g.nb(a.segments,c+1,0,b)))},H3=function(a,b,c,d,e,f){g.A.call(this);
this.policy=a;this.player=b;this.J=c;this.C=d;this.B=e;this.G=f;this.H=this.player.N();this.A=new G3;this.u=this.w=this.o=null;this.F=new g.H(this.ly,1E3,this);this.events=new g.O(this);g.C(this,this.F);g.C(this,this.events);this.events.L(b,"SEEK_COMPLETE",this.SA);this.SA();this.ly()},mta=function(a,b){var c=g.gw(b,a.policy,{}).Ub(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.u=g.mr(c,d,3,100).then(function(e){a.ga();var f=!(a.B?e.response:e.responseText)||400<=e.status,k=g.Gw(e);k?(e=g.gw(a.w,a.policy,{}),f=a.w,g.cw(f.u,e,k),f.requestId=e.get("req_id"),mta(a,a.w)):(f||null===a.C||(k=a.w.o[0],a.B?a.C(e.response,1E3*(k.startTime+a.player.Bb())):a.C(e.responseText,1E3*(k.startTime+a.player.Bb()))),a.w=null,a.u=null)});
a.w=b;lta(a.A,a.w.o[0].u)},I3=function(a,b){E3.call(this,b.N());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.hz(this.F.N())&&!this.o.u},nta=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.tL(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Az({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},ota=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},pta=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.tL(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},J3=function(a,b,c,d,e){E3.call(this,e||null);
c=c||g.qq(a).hl||"";c=c.split("_").join("-");this.A=g.sq(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},K3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.qD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.u=f;this.o=k},L3=function(a,b,c,d,e){g.qD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},qta=function(a){a=void 0===a?{}:a;
var b="_"+M3++;return new L3(0,0x8000000000000,0,b,a)},N3=function(a,b,c,d,e,f,k){var l={};
g.Ta(l,b);g.Ta(l,a.params);g.Ta(l,c);var m={};g.Ta(m,b.zb);a.params.zb&&g.Ta(m,a.params.zb);g.Ta(m,c.zb);l.zb=m;g.Q.call(this,{D:"div",I:"caption-window",O:{id:"caption-window-"+a.id,dir:1===l.Sc?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",I:"captions-text",O:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.R=!1;this.w=a;this.Z=this.T=null;this.Na=e;this.Ja=f;this.Ha=k;this.F=null;this.ca=.96*e;this.xa=.96*f;this.u=l;this.Ga=c;this.B=this.o["captions-text"];
this.Aa=null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.aa=d/360*16;this.type=0;this.ha=this.aa*rta(m);a=new g.Pr(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.qI,this);a.subscribe("dragmove",this.pI,this);a.subscribe("dragend",this.oI,this);this.sa=this.na=0;b="";this.u.windowOpacity&&(a=g.G1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+")");a={"background-color":b,display:!1===this.u.isVisible?"none":
"","text-align":sta[this.u.textAlign]};this.Aa&&(a["border-radius"]=b?this.ha/8+"px":"");if(this.A=2===this.w.params.Sc||3===this.w.params.Sc)b=this.element,c="vertical-rl",1===this.u.yu&&(c="vertical-lr"),g.je&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.vh(b,"-o-writing-mode",c),g.vh(b,"-webkit-writing-mode",c),g.vh(b,"writing-mode",c),g.vh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.w.params.Sc&&(g.vh(b,"text-orientation",""),g.vh(b,"transform","rotate(180deg)"));g.vh(this.element,
a);switch(this.u.Uf){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},rta=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},tta=function(a,b){var c={},d=b.background?b.background:a.u.zb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.zb.backgroundOpacity;d=g.G1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ha/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*rta(b)+"px";d=1;e=b.color||a.u.zb.color;if(b.color||null!=b.textOpacity)e=g.G1(e),d=null==b.textOpacity?a.u.zb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Qq&&(k=e=b.Qq);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.gl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.zb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ue&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.VF&&(c.visibility="hidden");1===b.Gx&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.jz||g.kz,3===a.w.params.Sc?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.cf||2===b.cf||3===b.cf||4===b.cf||5===b.cf)if(g.jz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.cf){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},uta=function(a){a.F=g.qe("SPAN");
g.vh(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},vta=function(a,b){var c=g.qe("SPAN");
g.vh(c,{display:"inline-block","white-space":"pre-wrap"});g.vh(c,tta(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.vh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.vh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},wta=function(a,b,c){a.R=a.R||!!c;
var d={};g.Ta(d,a.u.zb);g.Ta(d,c||b.o);g.Ta(d,a.Ga.zb);(c=!a.F)&&uta(a);for(var e=a.T&&a.Z&&g.Ob(d,a.Z)?a.T:vta(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.u,n=k[l];m&&!c?(uta(a),e=vta(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.re(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.jz||!g.zh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.zh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.le?g.vh(e,m,"1em"):g.vh(e,m,"0.5em")))}a.Z=d;a.T=e;a.C.push(b)},xta=function(){},P3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new O3(this);this.C=new O3(this);this.o=[];this.clear()},zta=function(a,b,c){if(255==a&&255==b||!a&&!b)return{hn:a,
jn:b,result:0};a=yta[a];b=yta[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{hn:a,jn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{hn:a,jn:b,result:2};return{hn:a,jn:b,result:3}},Bta=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Ata(a.B,b,c,d))},Cta=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?Bta(a,d.dw,d.ew,b):1==d.type&&a.w&496&&Ata(a.C,d.dw,d.ew,b)}a.o.length=0},Q3=function(){this.o=0},R3=function(){this.u=this.w=this.o=0},S3=function(){this.timestamp=this.re=0},T3=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new S3}this.o=this.u=this.row=0;this.style=new Q3;this.B=a;this.A=0},U3=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.w[m][p];
if(0!=t.re){0==c&&(c=m,d=p);n=String.fromCharCode(t.re);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.re||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.w[k][m],t=p.re,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Hta=function(a,b){switch(a){case 0:return Dta[(b&127)-32];
case 1:return Eta[b&15];case 2:return Fta[b&31];case 3:return Gta[b&31]}return 0},V3=function(a){return a.w[a.row][a.u]},W3=function(a,b,c){2<=b&&1<a.u&&(--a.u,V3(a).re=0);
var d=V3(a);d.timestamp=a.B.u+0;d.re=Hta(b,c);32>a.u&&a.u++},Ita=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].bi(a.w[c+e][f])},X3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},Y3=function(a){a.row=0<a.o?a.o:1;
a.u=1;X3(a,0,15)},Z3=function(a){this.A=a;
this.B=0;this.style=new Q3;this.C=new T3(a);this.F=new T3(a);this.G=new T3(a);this.u=this.C;this.w=this.F;this.o=this.u},$3=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:U3(d,c),Y3(a.u),Y3(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(U3(d,c),X3(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},Jta=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},Kta=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},O3=function(a){this.u=a;
this.o=new R3;this.B=0;this.w=new Z3(a);this.C=new Z3(a);this.A=this.w},Ata=function(a,b,c,d){a.o.update();
b=zta(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.hn;c=b.jn;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&W3(a,0,b),c&96&&W3(a,0,c),0!=b&&0!=c&&3==a.style.o&&U3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;Ita(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));X3(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:W3(b.o,0,32);break a;case 48:57==c?(d=b.o,V3(d).re=0,32>d.u&&d.u++):W3(b.o,1,c&15)}break;case 2:c&32&&W3(b.o,2,c&31);break;case 3:c&32&&W3(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Jta(b);break;
case 33:d=b.o;1<d.u&&(--d.u,V3(d).re=0);break;case 36:d=b.o;b=V3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:$3(b,2,d);break;case 38:$3(b,3,d);break;case 39:$3(b,4,d);break;case 40:W3(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);Y3(d);Kta(b);break;case 43:Kta(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:U3(a,d)}X3(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;U3(a,d);Ita(a,b,b+1,a.o-1);X3(a,a.row,1)}break;case 46:X3(b.w,0,15);break;case 47:U3(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,Jta(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},Mta=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.Rb){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=Lta(l.textContent,n.textContent,p.textContent,f.textContent,k);return new K3(a,b,e,c,l,d,m)}switch(m.Rb){case 9:case 10:m.cf=1;break;case 11:m.cf=2;break;case 12:m.cf=3;break;case 13:m.cf=4;break;case 14:m.cf=5}return new K3(a,b,e,c,l.textContent||"",d,m)},Lta=function(a,b,c,d,e){var f=g.gl(),k=
f?g.qe("DIV"):g.qe("RUBY"),l=g.qe("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.qe("DIV"):g.qe("RP");a.textContent=b;k.appendChild(a);b=f?g.qe("DIV"):g.qe("RT");b.textContent=c;k.appendChild(b);c=e.Rb;if(10===c||11===c||12===c||13===c||14===c)if(g.vh(b,"text-emphasis-style","filled circle"),g.vh(b,"text-emphasis-color","currentcolor"),g.vh(b,"webkit-text-emphasis","filled circle"),11===e.Rb||13===e.Rb)g.vh(b,"webkit-text-emphasis-position","under left"),g.vh(b,"text-emphasis-position","under left");c=!0;if(4===e.Rb||7===e.Rb||12===e.Rb||
14===e.Rb)g.vh(k,"ruby-position","over"),g.vh(k,"-webkit-ruby-position","before");else if(5===e.Rb||6===e.Rb||11===e.Rb||13===e.Rb)g.vh(k,"ruby-position","under"),g.vh(k,"-webkit-ruby-position","after"),c=!1;e=f?g.qe("DIV"):g.qe("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.vh(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.vh(f,"display","none"),f=f.nextElementSibling,g.vh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.vh(k.lastElementChild,"display","none"),d?(g.vh(k,"padding-top","0.6em"),g.vh(f,"top","0")):(g.vh(k,"padding-bottom","0.6em"),g.vh(f,"bottom","0")));return k},a4=function(){g.A.apply(this,arguments)},b4=function(a){a4.call(this);
this.A={};this.H={};this.J={};this.B="_"+M3++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},c4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},d4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},e4=function(a,b){var c=c4(a,b);
return void 0!=c?c:null},g4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return f4.test(c),c},Nta=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.J[d]:a.C);d=e4(b,"mh");null!=d&&(c.Gj=d);d=e4(b,"ju");null!=d&&(c.textAlign=d);d=e4(b,"pd");null!=d&&(c.Sc=d);d=e4(b,"sd");null!=d&&(c.yu=d);d=g4(b,"wfc");null!=d&&(c.windowColor=d);d=c4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},Ota=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.H[d]);d=e4(b,"ap");null!=d&&(c.Uf=d);d=c4(b,"cc");null!=d&&(c.Sg=d);d=c4(b,"ah");null!=d&&(c.We=d);d=c4(b,"rc");null!=d&&(c.Eg=d);d=c4(b,"av");null!=d&&(c.Gg=d);return c},Pta=function(a,b,c,d){var e={};
g.Ta(e,Ota(a,b));g.Ta(e,Nta(a,b));d?g.Ob(e,a.C)?(d=a.B,e=a.C):d="_"+M3++:d=b.getAttribute("id")||"_"+M3++;a=c4(b,"t")+c;b=c4(b,"d")||0x8000000000000;if(2===e.Sc||3===e.Sc)c=e.Eg,e.Eg=e.Sg,e.Sg=c;return new L3(a,b,0,d,e)},h4=function(a){a4.call(this);
this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map;this.C=a},i4=function(a){a=g.Od(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Qta=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!=a&&(f.Eg=a);b=b.ccColCount;void 0!=b&&(f.Sg=b);if(2===f.Sc||3===f.Sc)b=f.Eg,f.Eg=f.Sg,f.Sg=b;return new L3(c,d,0,e,f)},j4=function(a,b,c,d,e,f,k){N3.call(this,a,b,c,d,e,f,k);
this.type=1},k4=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},l4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},m4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},n4=function(a,b){a4.call(this);
this.u=a;this.track="CC3"==b.languageName?4:0;this.o=new P3;this.o.w=1<<this.track},o4=function(a){if("string"===typeof a)return!1;
a=new k4(a,8,0);return Rta(a)},Rta=function(a){if(!(a.o<a.u.byteLength)||1380139777!=m4(a))return!1;
a.version=l4(a);if(1<a.version)return!1;l4(a);l4(a);l4(a);return!0},p4=function(a,b,c,d,e,f,k){N3.call(this,a,b,c,d,e,f,k);
g.I(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.H=this.da=0;this.M=NaN;this.ya=0;this.Ba=null;this.ea=new g.H(this.HM,433,this);g.C(this,this.ea);g.vh(this.element,"overflow","hidden")},Sta=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},Tta=function(a){if(isNaN(a.M)){var b=a.u.Sg;
if(b){var c=g.qe("SPAN");g.Ae(c,"\u2013".repeat(b));g.vh(c,tta(a,a.u.zb));a.B.appendChild(c);a.M=c.offsetWidth;a.B.removeChild(c)}else a.M=0}return a.M},Uta=function(a,b){if(!b)return"";
a.A&&1!=a.w.params.yu&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},Vta=function(a){a.G=[].concat(g.na(document.getElementsByClassName("caption-visual-line")));
for(var b=a.w.params.Eg,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.H=d;a.J=Math.max(Tta(a),a.ya,Sta(a,a.B))},Wta=function(a,b){Vta(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.da){var d=0<c&&0==a.da;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),g.An(a.ea));g.vh(a.B,"transform",Uta(a,c));a.da=c}Vta(a)},q4=function(){a4.call(this)},Xta=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ue=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new K3(b,c,d,e.id,p.nodeValue,f||0<n,g.Mb(l)?void 0:l),m.push(p),e.o.push(p);else{var t={};g.Ta(t,l);Xta(a,b,c,d,e,!0,p,t,m)}}},r4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},Yta=function(a,b,c,d){d=Object.assign({Gj:0},d);
return new L3(a,b,c,"_"+M3++,d)},s4=function(a){g.A.call(this);
this.u=a;this.o=null},$ta=function(a){var b={};
if(a=B3(a))b.lang=a,Zta.test(a)&&(b.Sc=1);return b},v4=function(a){g.sL.call(this,a);
this.w=a.N();this.S=a.getVideoData();this.ya=g.NK(a);this.T=a;var b=null,c=g.po("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zn(c));this.ca=b;this.A={zb:{}};this.C={zb:{}};this.J=[];this.V={};this.aa={};this.M=!1;this.sa=g.uL(this.S,this.T);this.Aa=!!this.S.captionTracks.length;this.Ba=!!this.S.Bk;this.ha="3"===this.w.controlsType;b=a.app.B;c=!(!b||!b.Cm());this.xa=!(!b||!b.Ui());this.B=this.ha&&c&&!this.sa;this.H=!this.B&&this.ha&&this.xa&&this.sa;this.u=this.F=this.G=this.Z=this.ra=
null;this.da=new s4(this.w);g.C(this,this.da);c=b=this.o=null;this.B||(b=new g.wn(this.yC,void 0,this),g.C(this,b),c=new g.H(this.gO,2E3,this),g.C(this,c));this.ea=b;this.na=c;this.R=new g.O(this);g.C(this,this.R);this.B||this.R.L(a,"resize",this.Ju);this.R.L(a,"onPlaybackAudioChange",this.rK);this.R.L(a,g.tD("captions"),this.cH,this);this.R.L(a,"crx_captions",this.dH,this);t4(this,u4(this,"display-settings")||{})},w4=function(a){if(1===a.w.Rg||1===a.S.Rg||"alwayson"===g.EB(a.S,"yt:cc"))return!0;
if(2===a.w.Rg){var b=u4(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().Nq;return"ON"===c||"on"===g.EB(a.S,"yt:cc")},x4=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Nn||"FORCED_ON"===c.Nq},z4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Ba?!1:a.Aa?!1:!0);c=C3(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.EB(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(B3(c[f])===d[e])return c[f];return a.F&&a.F.Zq?a.F.Zq:(d=c.find(function(k){return k.isDefault}))?d:c[0]||y4(a)}return null},y4=function(a){return a.F&&a.F.Nn},A4=function(a){var b=y4(a);
return!!b&&a.o===b},aua=function(a,b){for(var c=a.T.app.B.eb().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},C4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&B4(a,"module-enabled",!!b));a.o=b;x4(a)&&(a.o=y4(a));a.load()},bua=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.Sc&&d&&Zta.test(d)&&(b.params.Sc=1);d=a.ya.getPlayerSize();switch(null!=b.params.Gj?b.params.Gj:1<b.o.length?1:0){case 1:return new j4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new p4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new N3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},t4=function(a,b,c){c=void 0===c?!1:c;
var d=D4.zb;a.A={};g.Ta(a.A,D4);a.A.zb={};g.Ta(a.A.zb,d);a.C={zb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;f4.test(f);e.zb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;f4.test(f);e.zb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||D4.windowColor;f4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.zb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.zb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Ue?3:d.bold?1:d.Ue?2:0);f=f.zb;switch(e){case 1:f.bold=!0;delete f.Ue;break;case 2:delete f.bold;f.Ue=!0;break;case 3:f.bold=!0;f.Ue=!0;break;default:delete f.bold,delete f.Ue}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.zb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=D4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.A;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.zb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.zb.fontFamily=f;a.loaded&&a.Ju();c&&B4(a,"display-settings",b)},dua=function(a,b){if(b&&!a.G){var c=qta({Sc:0,
lang:"en"});a.G=[c,new K3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.bL(a.player,a.G)}else!b&&a.G&&(cua(a,a.G),a.G=null)},cua=function(a,b){g.rT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.fb(this.J,c)},a);
g.xn(a.ea)},u4=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},B4=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.JL.prototype.Ck=g.ca(12,function(){for(var a=g.ce(document,"track",void 0,this.o),b=0;b<a.length;b++)g.ve(a[b])});
g.WQ.prototype.Ck=g.ca(11,function(){this.o.Ck()});
g.JL.prototype.Cm=g.ca(10,function(){return!!this.o.textTracks});
g.WQ.prototype.Cm=g.ca(9,function(){return this.o.Cm()});
g.JL.prototype.xk=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.WQ.prototype.xk=g.ca(7,function(a){this.o.xk(a)});
g.AC.prototype.Ui=g.ca(6,function(){});
g.JL.prototype.Ui=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.WQ.prototype.Ui=g.ca(4,function(){return this.o.Ui()});
g.Az.prototype.Qs=g.ca(2,function(a){return a?this.toString()===a.toString():!1});
g.Mt.prototype.Zn=g.ca(1,function(a){return(a=this.fg(a))?a.o:0});
g.zw.prototype.Zn=g.ca(0,function(){return 0});
var Zta=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,f4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(E3,g.A);E3.prototype.mB=function(){return!1};
E3.prototype.X=function(){this.Kh();g.A.prototype.X.call(this)};
g.r(F3,E3);F3.prototype.Cs=function(a,b,c){this.ga();b=this.Zk(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Kh();this.o=g.Iq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
F3.prototype.Ds=function(a){if(this.w)for(var b=g.q(this.w.captionTracks),c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
F3.prototype.Zk=function(a,b){var c=a.Ub(),d={fmt:b};if("srv3"==b||"3"==b||"json3"==b)g.gl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=B3(a));return g.sq(c,d)};
F3.prototype.Kh=function(){this.o&&this.o.abort()};
G3.prototype.contains=function(a){a=g.qb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
G3.prototype.length=function(){return this.segments.length/2};
g.r(H3,g.A);g.h=H3.prototype;g.h.X=function(){g.A.prototype.X.call(this);this.u&&this.u.cancel()};
g.h.SA=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.Bb();var b=this.o;this.o=g.Xa(this.J.jg(a).o);b!==this.o&&this.G&&this.G()};
g.h.reset=function(){this.A=new G3;this.u&&(this.u.cancel(),this.u=null)};
g.h.ly=function(){this.ga();var a;if(a=null!==this.o)a=this.o,a=a.o.wg(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.bh(),a.o[0].duration?(this.A.contains(a.o[0].u)||mta(this,a),this.o=g.Xa(a.o)):!g.R(this.H.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.player.Bb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.F.start()};
g.r(I3,E3);g.h=I3.prototype;g.h.Cs=function(a,b,c){this.Kh();b=ota(this,a.getId());b||(b=a.languageCode,b=this.o.u?pta(this,b,"386"):pta(this,b));if(b){var d=1E3*(b.index.Zn(b.index.Re())-b.index.fd(b.index.Re()));this.w=new H3(new g.yv,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.gt(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.mB=function(){var a=this.A;this.A=!1;return a};
g.h.Ds=function(a){var b;this.C?b=[new g.Az({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Az({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?nta(this,"386"):nta(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
g.h.Kh=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.Zk=function(){return""};
g.r(J3,E3);J3.prototype.Cs=function(a,b,c){this.ga();b=this.Zk(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Kh();this.o=g.Iq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
J3.prototype.Ds=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.sq(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
D3(this.u,new g.Az({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Kh();this.o=g.Iq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
J3.prototype.Zk=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=B3(a));return c=g.sq(c,d)};
J3.prototype.Kh=function(){this.o&&this.o.abort()};var sta=["left","right","center","justify"];var D4={windowColor:"#080808",windowOpacity:0,textAlign:2,Uf:7,We:50,Gg:100,zb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(K3,g.qD);K3.prototype.toString=function(){return g.qD.prototype.toString.call(this)};g.r(L3,g.qD);L3.prototype.toString=function(){return g.qD.prototype.toString.call(this)};
var M3=0;g.r(N3,g.Q);g.h=N3.prototype;g.h.qI=function(a,b){var c=g.Lh(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.I(this.element,"ytp-dragging")};
g.h.pI=function(a,b){var c=g.Oh(this.element),d=a-this.na-.02*this.Na,e=b-this.sa-.02*this.Ja,f=(d+c.width/2)/this.ca*3;f=Math.floor(g.Od(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.Od(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ca;d=100*g.Od(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.Od(c,0,1);this.w.params.Uf=l;this.w.params.Gg=c;this.w.params.We=d;this.u.Uf=l;this.u.Gg=c;this.u.We=d;this.MB()};
g.h.oI=function(){g.Ln(this.element,"ytp-dragging")};
g.h.MB=function(){this.Qi(this.C)};
g.h.Qi=function(a){var b=Math.min(this.ax(),this.ca),c=this.Zw(),d="";3===this.w.params.Sc&&(d="rotate(180deg)");g.vh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Fq(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.We+2;d=this.u.Uf;switch(d){case 0:case 3:case 6:b=this.u.zb.fontSizeIncrement;!g.R(this.Ha,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.Sc&&3!==this.u.Sc&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Gg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.vh(this.element,a)};
g.h.Fq=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.R||this.C.length>b)b=0,this.R=!1,this.C=[],this.F=this.Z=this.T=null,g.te(this.B);for(;b<a.length;b++)wta(this,a[b])};
g.h.ax=function(){return 0};
g.h.Zw=function(){return 0};
g.h.toString=function(){return g.Q.prototype.toString.call(this)};xta.prototype.B=function(){};P3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
P3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var yta=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Q3.prototype.set=function(a){this.o=a};
Q3.prototype.get=function(){return this.o};
R3.prototype.clear=function(){this.o=0};
R3.prototype.update=function(){this.o=2==this.o?1:0};
R3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
S3.prototype.bi=function(a){this.re=a.re;this.timestamp=a.timestamp};
S3.prototype.reset=function(){this.timestamp=this.re=0};
T3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
T3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.re?a+"_":a+String.fromCharCode(d.re)}a+="\n"}return a};
T3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var Dta=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Eta=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Fta=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Gta=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Z3.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
O3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(a4,g.A);a4.prototype.w=function(){return[]};
a4.prototype.reset=function(){};g.r(b4,a4);b4.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
b4.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ta(l,this.A[m]);m=d4(c,"b");null!=m&&(l.bold=
m);m=d4(c,"i");null!=m&&(l.Ue=m);m=d4(c,"u");null!=m&&(l.underline=m);m=e4(c,"et");null!=m&&(l.charEdgeStyle=m);m=e4(c,"of");null!=m&&(l.offset=m);m=g4(c,"bc");null!=m&&(l.background=m);m=g4(c,"ec");null!=m&&(l.Qq=m);m=g4(c,"fc");null!=m&&(l.color=m);m=e4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=c4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=c4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=c4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=e4(c,"rb");null!=m&&10!=m&&0!=m&&(l.Rb=10<m?m-1:m);
c=e4(c,"hg");null!=c&&(l.Gx=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=Nta(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=Ota(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=Pta(this,d,e,!1);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!d4(d,"a");n=
(c4(d,"t")||0)+n;var p=c4(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],z=[].concat(g.na(d.childNodes));z.length&&(this.F=null!=d.getAttribute("d"));for(var B=0;B<z.length;B++){var D=z[B],E=void 0;0<B&&(m=!0);var F=void 0;1===D.nodeType&&(F=D);if(F&&"s"===F.tagName){if((D=this.A[F.getAttribute("p")])&&D.Rb&&(1===D.Rb?(D=z.slice(B,B+4),4===D.length&&(E=Mta(n,p,l,m,t,D,this.A),
B+=3)):E=Mta(n,p,l,m,t,[F],this.A)),!E){var J=F;E=n;F=p;D=l;var ka=m,sa=t,rc=J.textContent?J.textContent:"",Yd=this.A[J.getAttribute("p")];J=c4(J,"t")||0;E=new K3(E+J,F-J,sa,D,rc,ka,Yd)}}else E=new K3(n,p,t,l,D.textContent||"",m,u);k.push(E);this.u=E}if(0<k.length)for(k[0].windowId===this.B&&(this.o=Pta(this,d,e,!0),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.o.push(k),c.push(k)}e=c}else e=[];return e};var eua=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(h4,a4);h4.prototype.reset=function(){this.u.clear()};
h4.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Ue=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!=f.ecEdgeColor&&(k.Qq=i4(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!=
f.fcForeColor&&(k.color=i4(f.fcForeColor));void 0!=f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!=f.bcBackColor&&(k.background=i4(f.bcBackColor));void 0!=f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Rb=10<l?l-1:l,k.cf=eua.get(k.Rb));f.hgHorizGroup&&(k.Gx=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=
f.mhModeHint&&(k.Gj=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&(k.Sc=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.yu=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=i4(f.wfcWinFillColor)),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),l=k,void 0!=f.ahHorPos&&(l.We=f.ahHorPos),
void 0!=f.apPoint&&(l.Uf=f.apPoint),void 0!=f.avVerPos&&(l.Gg=f.avVerPos),void 0!=f.ccCols&&(l.Sg=f.ccCols),void 0!=f.rcRows&&(l.Eg=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=Qta(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+M3++,l=Qta(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,p=n?6:5,
t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var z=t[m],B=z.utf8;if(B){var D=z.tOffsetMs||0,E=null;z.pPenId&&(E=this.o.get(z.pPenId));if(2===(null!=l.params.Gj?l.params.Gj:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(z=E&&1===E.Rb)if(z=m,z+3>=t.length||!t[z+1].pPenId||!t[z+2].pPenId||!t[z+3].pPenId)z=!1;else{var F=t[z+1].pPenId;(F=this.o.get(F))&&F.Rb&&2==F.Rb?(F=t[z+2].pPenId,F=this.o.get(F),!F||!F.Rb||3>F.Rb?z=!1:(F=t[z+3].pPenId,z=(F=this.o.get(F))&&F.Rb&&2==F.Rb?!0:
!1)):z=!1}if(z){D=t[m+1].utf8;z=t[m+3].utf8;F=t[m+2].utf8;var J=this.o.get(t[m+2].pPenId);B=Lta(B,D,F,z,J);n=new K3(e,f,p,k,B,n,E);m+=3}else n=new K3(e+D,f-D,p,l.id,B,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};g.r(j4,N3);j4.prototype.Fq=function(a){var b=this.w.o;N3.prototype.Fq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ta(d,c.o);g.Ta(d,fua);var e=c.o;var f=d}wta(this,c,d)}};
var fua={VF:!0};g.r(k4,xta);k4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+M3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new L3(c,d-c,5,f,{textAlign:0,Uf:0,We:2.5*b,Gg:5.33*a});e=new K3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(n4,a4);n4.prototype.w=function(a){a=new k4(a,a.byteLength,this.u);if(Rta(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=m4(a)*(1E3/45):1==a.version&&(a.A=4294967296*m4(a)+m4(a)),a.C=l4(a);0<a.C;a.C--){var b=l4(a),c=l4(a),d=l4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,dw:c,ew:d,order:b.o.length}))}Cta(this.o,a);return a.w}return[]};
n4.prototype.reset=function(){this.o.clear()};g.r(p4,N3);g.h=p4.prototype;g.h.MB=function(){g.Bn(this.ea)};
g.h.HM=function(){g.Ln(this.element,"ytp-rollup-mode");this.Qi(this.Ba,!0)};
g.h.Zw=function(){return this.A?this.J:this.H};
g.h.ax=function(){return this.A?this.H:this.J};
g.h.Qi=function(a,b){this.Ba=a;if(this.w.params.Eg){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.J;this.H=this.J=0;N3.prototype.Qi.call(this,a);Wta(this,b);N3.prototype.Qi.call(this,a)}else N3.prototype.Qi.call(this,a)};g.r(q4,a4);
q4.prototype.w=function(a,b){for(var c=[],d=a.split(gua),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!hua.test(f)){var l=E4.exec(f);if(l&&4<=l.length){var m=r4(l[1]),n=r4(l[2])-m;m+=k;var p,t=p=void 0,u=void 0,z=void 0,B=(l=l[3])?l.split(" "):[];l={textAlign:2};B=g.q(B);for(var D=B.next();!D.done;D=B.next())if(D=D.value.split(":"),2==D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(z=D[0],l.Gg=Number.parseInt(z,10),2==D.length&&(u=D[1].trim()));break;case "position":D=E.split(",");
t=D[0];l.We=Number.parseInt(t,10);2==D.length&&(p=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Gg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.We=0;break;case 1:l.We=100;break;default:l.We=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Uf=0>t||8<t?7:t;p=l;f=f.substring(E4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=Yta(m,n,5,t),n=new K3(m,n,5,k.id,p,!1,g.Mb(f)?void 0:f),c.push(k),c.push(n),k.o.push(n);else for(u=p.split(iua),1==u.length?(p=5,t=Yta(m,n,p,t)):(z=p=6,t=Object.assign({Sg:32},t),t=new L3(m,n,z,"_"+M3++,t)),c.push(t),z=m,l=0;l<u.length;l++)B=u[l],0==l%2?(D=g.H1("<html>"+B+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(B))):E=D.firstChild,Xta(this,z,n-(z-m),p,t,0<l,E,f,c)):z=r4(B)+k}E4.lastIndex=0}}return c};
var hua=/^NOTE/,gua=/(?:\r\n|\r|\n){2,}/,E4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),iua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(s4,g.A);s4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
s4.prototype.reset=function(){this.o&&this.o.reset()};
s4.prototype.X=function(){this.clear();g.A.prototype.X.call(this)};g.r(v4,g.sL);g.h=v4.prototype;g.h.X=function(){if(this.B||this.H){var a=this.T.app.B;a&&!a.ga()&&a.Ck()}else dua(this,!1);g.sL.prototype.X.call(this)};
g.h.load=function(){g.sL.prototype.load.call(this);var a=!g.R(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u)this.o&&(this.da.clear(),this.B?aua(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Cs(this.o,"json3",(0,g.x)(this.rN,this)),!a||this.B||this.H||A4(this)||this.player.ma("captionschanged",A3(this.o))),a||(this.o&&!A4(this)?this.player.ma("captionschanged",A3(this.o)):this.player.ma("onCaptionsTrackListChanged"));
else{var b;this.sa?b=new I3(this.S.la,this.player):this.Aa?b=new F3(this.w,this.S,this.player.getAudioTrack()):b=new J3(this.S.Bk,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.EB(this.S,"yt:cc_default_lang")||this.w.jc,this.S.Lq,this.w);this.u=b;g.C(this,this.u);b.Ds((0,g.x)(this.qN,this))}};
g.h.unload=function(){this.B&&this.o?aua(this,!1):(this.na&&g.Cn(this.na),g.vQ(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Kh(),this.da.clear(),this.G&&g.bL(this.player,this.G),this.Ju());g.sL.prototype.unload.call(this);var a=g.W(this.player.app);a&&g.RH(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ha?this.B||this.H:x4(this)||w4(this))&&this.load()};
g.h.qN=function(){var a;this.M||w4(this)?a=z4(this,this.M):x4(this)&&(a=y4(this));if(this.B||this.H){for(var b=C3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Bz(e),srclang:B3(e),id:e.toString()};this.H||(f.src=this.u.Zk(e,"vtt"));e===a&&(f["default"]=1);c.push(g.pe("TRACK",f))}a=this.T.app.B;a.xk(c);c=a.eb();this.xa&&this.R.L(c.textTracks,"change",this.sN)}else!this.o&&a&&C4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.sN=function(){for(var a=this.T.app.B.eb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=C3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&C4(this,b,!0)};
g.h.VO=function(){!this.o&&this.B||this.unload()};
g.h.rN=function(a,b,c,d){if(a){this.u.mB()&&(this.J=[],g.vQ(this.T.app,"captions",void 0),g.xn(this.ea),this.da.reset());var e=this.da;c=c||0;d=d||0;if(e.u.fa("html5_disable_rawcc_killswitch")){if("string"!==typeof a){var f=new DataView(a);8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.bu(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),o4(a)||(a=jta(new Uint8Array(a))))}}else"string"===typeof a||o4(a)||(f=new DataView(a),a=8>=f.byteLength||1718909296!==f.getUint32(4)?"":(f=g.bu(f,0,
1835295092))&&f.size?jta(new Uint8Array(a.slice(f.dataOffset,f.dataOffset+f.size))):"");if(a)try{if("string"!==typeof a){var k=a,l=c,m=d;if(!o4(k))throw Error("Invalid binary caption track data");e.o||(e.o=new n4(m,b));var n=e.o.w(k,l)}else{if("WEBVTT"==a.substring(0,6))b=a,m=c,e.o||(e.o=new q4),l=e.o.w(b,m),.01>Math.random()&&g.Ko(Error("Deprecated subtitles format in web player: WebVTT")),k=l;else b:{l=a;if("{"===l[0])try{e.o||(e.o=new h4($ta(b)));k=e.o.w(l,c);break b}catch(D){g.M(D);k=[];break b}m=
g.H1(l);if(!m||!m.firstChild){var p=Error("Invalid caption track data");p.params=l;throw p;}if("timedtext"==m.firstChild.tagName){if(3==parseInt(m.firstChild.getAttribute("format"),10)){e.o||(e.o=new b4($ta(b),e.u));k=e.o.w(m,c);break b}var t=Error("Unsupported subtitles format in web player (Format2)");t.params=l;throw t;}if("transcript"==m.firstChild.tagName){var u=Error("Unsupported subtitles format in web player (Format1)");u.params=l;throw u;}var z=Error("Invalid caption track data");z.params=
l;throw z;}n=k}var B=n}catch(D){g.M(D),e.clear(),B=[]}else B=[];g.bL(this.player,B);!this.M||this.H||A4(this)||g.Wy(this.w)||g.Xy(this.w)||(g.Cn(this.na),B=qta({Uf:0,We:5,Gg:5,Eg:2,textAlign:0,Sc:0,lang:"en"}),this.Z=[B],e=["Click "," for settings"],this.ra||(n=new g.Bt(g.mM()),g.C(this,n),this.ra=n.element),n=B.end-B.start,(b=g.Bz(this.o))&&this.Z.push(new K3(B.start,n,0,B.id,b)),this.Z.push(new K3(B.start,n,0,B.id,e[0]),new K3(B.start,n,0,B.id,this.ra,!0),new K3(B.start,n,0,B.id,e[1],!0)),g.bL(this.player,
this.Z),g.An(this.na));!this.M||this.H||A4(this)||(B4(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(B=g.W(this.player.app))&&g.RH(B.B));this.M=!1}};
g.h.cH=function(a){this.J.push(a);g.xn(this.ea)};
g.h.dH=function(a){g.fb(this.J,a);this.u instanceof I3&&this.u.C&&g.rT(this.player.app,[a],void 0);g.xn(this.ea)};
g.h.ZN=function(a){if(a instanceof L3){var b=this.V[a.id];b&&b.w!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=bua(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.gO=function(){cua(this,this.Z);this.Z=null};
g.h.yC=function(){this.ea.stop();g.Nb(this.aa);this.J.sort(g.sD);var a=this.J;if(this.G){var b=(0,g.we)(a,function(c){return-1===this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.ZN,this);g.zb(this.V,function(c,d){this.aa[d]?(c.element.parentNode||g.fL(this.player,c.element,4),c.Qi(this.aa[d])):(c.dispose(),delete this.V[d])},this)};
g.h.nO=function(){t4(this,{},!0);g.R(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.jF=function(){var a=D4.zb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ue?3:a.bold?1:a.Ue?2:0,textOpacity:a.textOpacity,windowColor:D4.windowColor,windowOpacity:D4.windowOpacity};var b=u4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.EC=function(a,b){b=void 0===b?!1:b;var c={};g.Ta(c,u4(this,"display-settings"));g.Ta(c,a);t4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.Ju=function(){!this.B&&this.loaded&&(g.zb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.yC())};
g.h.Nc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Od(b,-2,4);this.EC({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&C4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.Db&&B4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Pa(b))break;if(g.Mb(b)){C4(this,null,!0);break}for(var d=C3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!=b.languageName||(c=b.translationLanguage?
ita(f,b.translationLanguage):f)}!c||c==this.o&&this.loaded||C4(this,c,!0)}else return this.loaded&&this.o&&!A4(this)?A3(this.o):{};return"";case "tracklist":return this.u?(0,g.Ec)(C3(this.u.u,!(!b||!b.includeAsr)),function(k){return A3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||dua(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.Db&&a.push("stickyLoading");return a};
g.h.EG=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.h.PO=function(){this.loaded&&this.o&&!A4(this)?(B4(this,"module-enabled",!1),this.unload(),x4(this,!0)&&C4(this,y4(this),!1)):C4(this,A4(this)||!this.o?z4(this,!0):this.o,!0)};
g.h.rK=function(){var a=A4(this);x4(this,a)?C4(this,this.player.getAudioTrack().Nn,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.ha?this.B||this.H:x4(this)||w4(this))&&(a?C4(this,z4(this),!1):this.load()))};g.HL.captions=v4;})(_yt_player);
