(function(g){var window=this;var Z5=function(a,b,c){a.w.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Fm(a.w,b,c)},fua=function(a,b){var c=[];
g.Oj(b,function(d){try{var e=g.In.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Hn(e)&&c.push(d)},a);
return c},gua=function(a,b){var c=fua(a,b);
(0,g.y)(c,function(d){g.In.prototype.remove.call(this,d)},a)},hua=function(a){if(a.Vc){if(a.Vc.locationOverrideToken)return{locationOverrideToken:a.Vc.locationOverrideToken};
if(null!=a.Vc.latitudeE7&&null!=a.Vc.longitudeE7)return{latitudeE7:a.Vc.latitudeE7,longitudeE7:a.Vc.longitudeE7}}return null},iua=function(a,b){g.bb(a,b)||a.push(b)},jua=function(a,b){var c=b instanceof g.$b?b:g.dc(b,/^data:image\//i.test(b));
a.src=g.ac(c)},b6=function(){},kua=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},lua=function(a,b,c,d){var e=new g.um(null,void 0);
a&&g.vm(e,a);b&&g.wm(e,b);c&&g.xm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.uo[a]=!0;
var c=g.so();c&&c.publish.apply(c,arguments);g.uo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.qm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",mua(this,a.capabilities||""),nua(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},mua=function(a,b){a.capabilities.clear();
(0,g.be)(b.split(","),g.Sa(g.A.contains,oua)).forEach(function(c){a.capabilities.add(c)})},nua=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},pua=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},qua=function(a){return new e6(a)},rua=function(a){return g.Ma(a)?(0,g.ic)(a,qua):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ma(a)?"["+(0,g.ic)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},sua=function(a){return(0,g.ic)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Za(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Xr)(),c=(0,g.Wr)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},tua=function(){var a=(0,g.Wr)();
a&&gua(a,a.o.lf(!0))},m6=function(){var a=g.Zr("yt-remote-connected-devices")||[];
g.sb(a);return a},uua=function(a){if(g.cb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},vua=function(a){g.Yr("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Zr("yt-remote-device-id");a||(a=i6(),g.Yr("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.bb(a,b);g.$r()&&g.ub(a,b);a=uua(a);if(g.cb(a))try{g.lq("remote_sid")}catch(c){}else try{g.jq("remote_sid",a.join(","),-1)}catch(c){}},wua=function(){return g.Zr("yt-remote-session-browser-channel")},xua=function(){return g.Zr("yt-remote-local-screens")||[]},yua=function(){g.Yr("yt-remote-lounge-token-expiration",!0,86400)},zua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ic)(xua(),function(d){return d.loungeToken}),c=(0,g.ic)(a,function(d){return d.loungeToken});
(0,g.$h)(c,function(d){return!g.bb(b,d)})&&yua();
g.Yr("yt-remote-local-screens",a,31536E3)},Aua=function(a,b){g.Yr("yt-remote-session-browser-channel",a);
g.Yr("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.bb(c,d)||c.push(d);vua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.fb(a,o6());vua(a)},Bua=function(){if(!r6){var a=g.Tn();
a&&(r6=new g.Cn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Cua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Dua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Eua(a.shift(),function(){s6(a)}):t6()},Fua=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Eua=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Dua();
a&&a(!1,"No cast extension found")},Hua=function(){if(Gua){var a=2,b=Dua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Eua("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Iua=function(){Hua();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.B.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Cd=b;this.B=(0,g.x)(this.jF,this);this.o=!1;this.u=0;this.w=this.Ea=null;this.A=[]},v6=function(a,b,c){g.B.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Cd=b;this.u=(0,g.x)(this.kF,this);this.o=[]},w6=function(a){a.Ea=g.zf(a.u,a.Cd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return kua(a)},y6=function(){},z6=function(){},Jua=function(){},Lua=function(a){return(a=Kua(a))?new ActiveXObject(a):new XMLHttpRequest},Kua=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.P1(this);this.u=new g.yf;this.u.setInterval(250)},Nua=function(a,b,c){a.uj=1;
a.Pg=$5(b.clone());a.Ki=c;a.C=!0;Mua(a,null)},B6=function(a,b,c,d,e){a.uj=1;
a.Pg=$5(b.clone());a.Ki=null;a.C=c;e&&(a.EB=!1);Mua(a,d)},Mua=function(a,b){a.dk=(0,g.H)();
C6(a);a.Ah=a.Pg.clone();a6(a.Ah,"t",a.F);a.Lm=0;a.Mc=a.o.Vq(a.o.ym()?b:null);0<a.Hr&&(a.vp=new v6((0,g.x)(a.EC,a,a.Mc),a.Hr));a.A.ka(a.Mc,"readystatechange",a.ZN);var c=a.li?g.A.clone(a.li):{};a.Ki?(a.bq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Mc.send(a.Ah,a.bq,a.Ki,c)):(a.bq="GET",a.EB&&!g.Qd&&(c.Connection="close"),a.Mc.send(a.Ah,a.bq,null,c));a.o.bf(1)},Qua=function(a,b,c){for(var d=!0;!a.Sh&&a.Lm<c.length;){var e=Oua(a,c);
if(e==D6){4==b&&(a.dh=4,E6(15),d=!1);break}else if(e==Pua){a.dh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.dh=1,E6(17),d=!1);a.df=a.df&&d;d||(G6(a),H6(a))},Oua=function(a,b){var c=a.Lm,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Pua;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Lm=d+c;return e},Sua=function(a,b){a.dk=(0,g.H)();
C6(a);var c=b?window.location.hostname:"";a.Ah=a.Pg.clone();Z5(a.Ah,"DOMAIN",c);Z5(a.Ah,"t",a.F);try{a.jf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.dh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in Rua)k=I6[l]=Rua[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Cc(g.Eb("b/12014412"),d+"</body></html>");a.jf.open();a.jf.write(g.xc(c));a.jf.close();a.jf.parentWindow.m=(0,g.x)(a.vN,a);a.jf.parentWindow.d=(0,g.x)(a.KA,a,!0);a.jf.parentWindow.rpcClose=(0,g.x)(a.KA,a,!1);c=a.jf.createElement("DIV");a.jf.parentWindow.document.body.appendChild(c);d=g.cc(a.Ah.toString());d=g.Lc(g.ac(d));d=g.Cc(g.Eb("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Dc(c,d);a.o.bf(1)},C6=function(a){a.Ju=(0,g.H)()+a.B;
Tua(a,a.B)},Tua=function(a,b){if(null!=a.tk)throw Error("WatchDog timer not null");
a.tk=J6((0,g.x)(a.DN,a),b)},K6=function(a){a.tk&&(g.v.clearTimeout(a.tk),a.tk=null)},H6=function(a){a.o.qx()||a.Sh||a.o.ip(a)},G6=function(a){K6(a);
g.ne(a.vp);a.vp=null;a.u.stop();g.hpa(a.A);if(a.Mc){var b=a.Mc;a.Mc=null;b.abort();b.dispose()}a.jf&&(a.jf=null)},F6=function(a,b){try{a.o.EA(a,b),a.o.bf(4)}catch(c){}},Vua=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Uua(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Vua(a,b,c,d,f)},f)})}},Uua=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
jua(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Wua=function(a){this.o=a;
this.u=new y6},Xua=function(a){var b=M6(a.o,a.Ck,"/mail/images/cleardot.gif");
$5(b);Vua(b.toString(),5E3,(0,g.x)(a.fE,a),3,2E3);a.bf(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Wd=new A6(a,void 0,void 0,void 0),a.Wd.li=a.Fr,b=a.o,b=M6(b,b.ym()?a.bl:null,a.Gr),E6(5),!g.Od||g.sd(10))a6(b,"TYPE","xmlhttp"),B6(a.Wd,b,!1,a.bl,!1);else{a6(b,"TYPE","html");var c=a.Wd;a=!!a.bl;c.uj=3;c.Pg=$5(b.clone());Sua(c,a)}},P6=function(a){g.Ne.call(this);
this.headers=new g.qm;this.S=a||null;this.w=!1;this.O=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.aa=this.G=this.U=!1;this.F=0;this.J=null;this.ea="";this.P=this.Z=!1},Yua=function(a){return g.Od&&g.rd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Zua=function(a){return"content-type"==a.toLowerCase()},ava=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;$ua(a);Q6(a)},$ua=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},cva=function(a){if(a.w&&"undefined"!=typeof g.U1)if(a.O[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.zf(a.AA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Vc(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!bva.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";$ua(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){dva(a);
var c=a.o,d=a.O[0]?g.Ja:null;a.o=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},dva=function(a){a.o&&a.P&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},eva=function(a,b){this.o=a;
this.map=b;this.context=null},fva=function(a){g.pe.call(this,"statevent",a)},gva=function(a,b){g.pe.call(this,"timingevent",a);
this.size=b},hva=function(a){g.pe.call(this,"serverreachability",a)},kva=function(a){iva(a);
if(3==a.o){var b=a.Wl++,c=a.Rn.clone();Z5(c,"SID",a.w);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.uj=2;b.Pg=$5(c.clone());jua(new Image,b.Pg.toString());b.dk=(0,g.H)();C6(b)}jva(a)},lva=function(a){a.DE(1,0);
a.Rn=M6(a,null,a.Er);W6(a)},iva=function(a){a.Tg&&(a.Tg.abort(),a.Tg=null);
a.kc&&(a.kc.cancel(),a.kc=null);a.Qf&&(g.v.clearTimeout(a.Qf),a.Qf=null);X6(a);a.Qd&&(a.Qd.cancel(),a.Qd=null);a.Xg&&(g.v.clearTimeout(a.Xg),a.Xg=null)},mva=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new eva(a.NJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Qd||a.Xg||(a.Xg=J6((0,g.x)(a.JA,a),0),a.nj=0)},ova=function(a,b){if(1==a.o){if(!b){a.Wl=Math.floor(1E5*Math.random());
var c=a.Wl++,d=new A6(a,"",c,void 0);d.li=null;var e=Y6(a),f=a.Rn.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);Nua(d,f,e);a.Qd=d;a.o=2}}else 3==a.o&&(b?nva(a,b):0==a.u.length||a.Qd||nva(a))},nva=function(a,b){if(b)if(6<a.Th){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Wl-1;var d=Y6(a)}else c=b.G,d=b.Ki;else c=a.Wl++,d=Y6(a);var e=a.Rn.clone();Z5(e,"SID",a.w);Z5(e,"RID",c);Z5(e,"AID",a.Gj);V6(a,e);c=new A6(a,a.w,c,a.nj+1);c.li=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Qd=c;Nua(c,e,d)},V6=function(a,b){if(a.yd){var c=a.yd.Mw();
c&&g.A.forEach(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Th&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Th?e:f-d;try{g.A.forEach(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},pva=function(a){a.kc||a.Qf||(a.F=1,a.Qf=J6((0,g.x)(a.IA,a),0),a.dj=0)},Z6=function(a){if(a.kc||a.Qf||3<=a.dj)return!1;
a.F++;a.Qf=J6((0,g.x)(a.IA,a),qva(a,a.dj));a.dj++;return!0},N6=function(a,b,c){a.Yp=c;
a.sf=b.hg;a.C||lva(a)},X6=function(a){null!=a.ai&&(g.v.clearTimeout(a.ai),a.ai=null)},qva=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.yd&&(c=null);var d=(0,g.x)(a.LO,a);c||(c=new g.um("//www.google.com/images/cleardot.gif"),$5(c));Uua(c.toString(),1E4,d)}else E6(2);rva(a,b)},rva=function(a,b){a.o=0;
a.yd&&a.yd.Zv(b);jva(a);iva(a)},jva=function(a){a.o=0;
a.sf=-1;if(a.yd)if(0==a.A.length&&0==a.u.length)a.yd.Nq();else{g.jb(a.A);var b=g.jb(a.u);a.A.length=0;a.u.length=0;a.yd.Nq(b)}},M6=function(a,b,c){var d=g.Cm(c);
if(""!=d.o)b&&g.wm(d,b+"."+d.o),g.xm(d,d.A);else{var e=window.location;d=lua(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Pk&&g.A.forEach(a.Pk,function(f,k){Z5(d,k,f)});
Z5(d,"VER",a.Th);V6(a,d);return d},J6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new fva(a7,a))},sva=function(){},tva=function(){this.o=[];
this.u=[]},uva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.o=new g.I(this.mN,0,this);g.C(this,this.o);this.Cd=5E3;this.u=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Bn;this.u=new b7(this.oO,this);this.o=null;this.ub=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.P=c||!1},vva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Yp,sessionId:a.o.w,arrayId:a.o.Gj}},wva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&ova(a.o),kva(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},xva=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Vc(4,a))||"";b&&(this.port=":"+b);this.domain=g.Wc(a)||"";a=g.oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Wb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.fd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.A,d,!0),onError:g.Sa(a.w,e),Td:g.Sa(a.B,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.bq(b,a)},Bva=function(){var a=yva;
zva();h7.push(a);Ava(h7)},i7=function(a,b){zva();
var c=h7,d=Cva(a,String(b));g.cb(c)?Dva(d):(Ava(c),(0,g.y)(c,function(e){e(d)}))},zva=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},Dva=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Ava=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Cva=function(a,b){var c=((0,g.H)()-Eva)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},Fva=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Gva=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.be)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Fva(a,b[d])||c;return c},Hva=function(a,b){var c=a.o.length;
a.o=(0,g.be)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ea=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},Iva=function(a){if(a.o.length){var b=(0,g.ic)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.uF,a),(0,g.x)(a.tF,a))}},o7=function(a){var b=rua(xua());
b=(0,g.be)(b,function(c){return!c.uuid});
return Gva(a,b)},q7=function(a,b){zua((0,g.ic)(a.o,pua));
b&&yua()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.Zr("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.qk(this.o))},Jva=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(g.A.Qc(b)!=g.A.Qc(a.o))var c=!1;
else{c=g.A.Eb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.qk(a.o)),a.o=b,a.R("screenChange"));Kva(a)},u7=function(a){isNaN(a.w)||g.ro(a.w);
a.w=g.po((0,g.x)(a.Xt,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Lva=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Rb("Requesting availability of screen w/o lounge token.")});
return b},Kva=function(a){a=g.A.Eb(g.A.filter(a.o,function(b){return b}));
g.sb(a);a.length?g.Yr("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Mva(this)},Ova=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);Jva(a.u,l,function(m){e(m?l:null)})}else c?Nva(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Jva(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},Pva=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Nva=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.bq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Qva=function(a){a.o=a.w.ke();
for(var b=g.A.eC(a.B),c=0,d=a.o.length;c<d;++c){var e=a.o[c];e.uuid=b[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},Mva=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.DF,a));Qva(a);a.A=rua(g.Zr("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.ke,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Yr("yt-remote-automatic-screen-cache",(0,g.ic)(a.A,pua)));x7(a);a.B[b.uuid]=b.id;g.Yr("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Zr("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.O=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.O,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.vP,this);this.B=(0,g.x)(this.LN,this);this.A=g.po((0,g.x)(function(){Rva(this,null)},this),12E4)},Sva=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.qk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.qk(b))},Rva=function(a,b){g.ro(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.kp,a),d=(0,g.x)(a.oe,a);a.hx(b,c,d,5)}}else a.oe(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.S=c;this.B=null;this.F=g.Ja;this.C=NaN;this.P=(0,g.x)(this.yP,this);this.o=g.Ja},Tva=function(a){a.o=a.H.LC(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.kp(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.oe(b)},a))},Uva=function(a){var b={};
b.pairingCode=a.J;b.theme=a.S;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Bua()&&(b.env_useStageMdx=1);return g.dd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.po((0,g.x)(this.Hj,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.tM,this)},Vva=function(a,b){return b?g.Za(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},yva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.ne(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.HA,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.Hj(null)):a.R("yt-remote-cast2-session-change",null))},Wva=function(a){var b=a.u.KC(),c=a.o&&a.o.u;
a=(0,g.ic)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Vva(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bwa=function(a,b,c,d,e,f,k){Xva()?Yva(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Zva(a,c):(window.__onGCastApiAvailable=function(l,m){l?Zva(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),$va(),c(!1))},d?g.Bo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Iua():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(Hua(),s6(awa.map(Fua))))):H7("Cannot initialize because not running Chrome")},$va=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);cwa(!1);g.xo(M7);M7.length=0},N7=function(){return!!g.Zr("yt-remote-cast-installed")},dwa=function(){var a=g.Zr("yt-remote-cast-receiver");
return a?a.friendlyName:null},ewa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},fwa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.wo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Xva=function(){var a=0<=g.oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Rs||a},gwa=function(a,b){L7().init(a,b)},Yva=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Yr("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Yr("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Yr("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Zva=function(a,b){K7(!0);
I7(!1);gwa(a,function(c){c?(cwa(!0),g.yo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),$va());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Yr("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},cwa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.J=!1;this.H=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.J=!1;a.hasNext=!1;a.F=0;a.C=(0,g.H)();a.B=0;a.u=0;a.G=0;a.H=0;a.A=NaN;a.w=!1},T7=function(a){return 1==a.playerState?((0,g.H)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.H)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.A.Im(a.o);b.hasPrevious=a.J;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new tva;this.w=this.u=null;this.H=(0,g.x)(this.uK,this);this.F=(0,g.x)(this.Yl,this);this.G=(0,g.x)(this.tK,this);this.J=(0,g.x)(this.EK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Mu,this),hwa(this))):c=3;0!=c&&(b?this.Mu(c):g.po((0,g.x)(function(){this.Mu(c)},this),0));
var d=fwa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},hwa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Sa(this.qM,b),this))},a)},iwa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){50>a.B.Qc()&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){iwa(a);
a.A.setPlayerContextData(X7(b));hwa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.Yl(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.Yl(a.w.media[0]))},jwa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Rb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Rb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.P=!1;this.G=this.F=this.H=this.J=NaN;this.O=[];this.A=this.C=this.w=this.Sa=this.o=null;this.U=a;this.O.push(g.cp(window,"beforeunload",(0,g.x)(this.mF,this)));this.u=[];this.Sa=new R7;this.S=b.id;this.o=kwa(this,c);this.o.subscribe("handlerOpened",this.yK,this);this.o.subscribe("handlerClosed",this.vK,this);this.o.subscribe("handlerError",this.wK,this);this.o.subscribe("handlerMessage",this.xK,this);xva(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.$r()&&g.Yr("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},kwa=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},lwa=function(a){a.B=g.po((0,g.x)(function(){g8("Connecting timeout");
this.kj(1)},a),2E4)},i8=function(a){g.ro(a.B);
a.B=NaN},j8=function(a){g.ro(a.J);
a.J=NaN},mwa=function(a){k8(a);
a.H=g.po((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.ro(a.H);
a.H=NaN},owa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.fx()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),nwa(a)):a.kj(1)},pwa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.A.isEmpty(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.R("remotePlayerChange"))},qwa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.R("remoteQueueChange")},swa=function(a,b){b.params=b.params||{};
qwa(a,b);rwa(a,b);a.R("autoplayDismissed")},rwa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?mwa(a):k8(a);a.R("remotePlayerChange")},twa=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.R("remotePlayerChange")}},uwa=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.R("remotePlayerChange")},vwa=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},wwa=function(a,b){var c="true"==b.params.hasNext;
a.Sa.J="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.R("previousNextChange")},nwa=function(a){g.ro(a.G);
a.G=g.po((0,g.x)(a.kj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.qk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Bd=a;this.u=[];this.u.push(this.Bd.$_s("screenChange",(0,g.x)(this.tP,this)));this.u.push(this.Bd.$_s("onlineScreenChange",(0,g.x)(this.TL,this)))},Bwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.M("MDX_CONFIG")||b;tua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Bua()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));xwa();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);bwa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.qk(b)),s8.push(g.wo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.wo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.wo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.wo("yt-remote-cast2-session-change",ywa)),s8.push(g.wo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),ewa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.fo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.qk(a)),zwa(a),c.start(),q8()||Awa())},Dwa=function(){var a=Cwa();
N7()&&g.Zr("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Cwa=function(){var a=p8().Bd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return sua(a)},y8=function(){var a=Ewa();
!a&&N7()&&dwa()&&(a={key:"cast-selector-receiver",name:dwa()});return a},Ewa=function(){var a=Cwa(),b=w8();
b||(b=u8());return g.Za(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().ke();return k6(b,a)},ywa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Fwa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},Gwa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Fwa("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.$r();
if(!a)return null;var b=p8().ke();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Fwa(a.id);var c=new f8(n8,a,v8());c.connect(b,Gwa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Awa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),ewa(),r8("Skipping connecting because no session screen found."))},xwa=function(){var a=v8();
if(g.A.isEmpty(a)){a=o6();var b=g.Zr("yt-remote-session-name")||"",c=g.Zr("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},zwa=function(a){a?(g.Yr("yt-remote-session-app",a.app),g.Yr("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.B.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.C(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.pL);this.w.L(b,"captionschanged",this.sK);this.w.L(b,"captionssettingschanged",this.VB);this.w.L(b,"videoplayerreset",this.lp);this.w.L(b,"mdxautoplaycancel",this.eE);this.S=this.w.L(b,"onVolumeChange",this.nA);this.G=!1;this.o=c;c.ga();c.subscribe("proxyStateChange",this.DA,this);c.subscribe("remotePlayerChange",this.hm,this);c.subscribe("remoteQueueChange",this.lp,this);c.subscribe("autoplayUpNext",
this.bA,this);c.subscribe("previousNextChange",this.zA,this);c.subscribe("nowAutoplaying",this.vA,this);c.subscribe("autoplayDismissed",this.aA,this);this.suggestion=null;this.H=new g.oC(64);this.A=new g.I(this.TB,500,this);g.C(this,this.A);this.C=new g.I(this.UB,1E3,this);g.C(this,this.C);this.P=new u6(this.VO,0,this);g.C(this,this.P);this.F={};this.O=new g.I(this.wC,1E3,this);g.C(this,this.O);this.J=new v6(this.bI,1E3,this);g.C(this,this.J);this.U=g.Ja;this.VB();this.lp();this.hm()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.O=b||0;c.player.R("progresssync",b,d)},Hwa=function(a){H8(a,0);
a.A.stop();I8(a,new g.oC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.A.extend(c,b));a.o.KB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.uf,hua(c));I8(a,new g.oC(1))},Iwa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{sT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.uC(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.aS(a.u.app,d);a.H=b;Jwa(a.B,c,b)}},M8=function(){g.S.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.gL(this,250);g.C(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.S.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.iL()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.gL(this,250);g.C(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);Kwa(this,g.hK(a))},Kwa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.ML("Error on $RECEIVER_NAME",c):g.vC(b)||g.X(b,4)?g.ML("Playing on $RECEIVER_NAME",c):g.ML("Connected to $RECEIVER_NAME",c);a.ia("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.KN.call(this,"Play on",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.MK.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.S=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.oC(64);this.O=0;this.H=-1;this.C=null;if(!g.Py(this.player.N())){a=this.player;var b=g.TB(a);b&&(b=b.Ol())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.zK(a,b.element,4);this.C=new M8;g.C(this,this.C);g.zK(a,this.C.element,4);this.P=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Jwa=function(a,b,c){a.F=
c;
a.player.R("presentingplayerstatechange",new g.AC(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.T(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.P||!a.C);if(c?0:g.Xy(a.player.N())||"WEB_EMBEDDED_PLAYER"==a.player.N().deviceParams.c)g.vC(g.hK(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.PN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.u.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2==a.player.app.U||1==a.player.app.U)&&g.T(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.uf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=hua(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.qk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().ke(),(c=k6(c,b.key))&&A8(c,1))}},Rua={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},Lwa={},oua={WP:"atp",CS:"ska",rS:"que",KR:"mus",BS:"sus",WQ:"dsp",yS:"seq"};
d6.prototype.Yh=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
d6.prototype.ob=function(a){return a?this.id==a.id:!1};
var r6,n6="",Gua=Cua("loadCastFramework")||Cua("loadCastApplicationFramework"),awa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(u6,g.B);g.h=u6.prototype;g.h.iF=function(a){this.A=arguments;this.o=!1;this.Ea?this.w=(0,g.H)()+this.Cd:this.Ea=g.zf(this.B,this.Cd)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Db.X.call(this)};
g.h.jF=function(){this.w?(this.Ea=g.zf(this.B,this.w-(0,g.H)()),this.w=null):(this.Ea=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Ua(v6,g.B);g.h=v6.prototype;g.h.tj=!1;g.h.al=0;g.h.Ea=null;g.h.nx=function(a){this.o=arguments;this.Ea||this.al?this.tj=!0:w6(this)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null,this.tj=!1,this.o=[])};
g.h.pause=function(){this.al++};
g.h.resume=function(){this.al--;this.al||!this.tj||this.Ea||(this.tj=!1,w6(this))};
g.h.X=function(){v6.Db.X.call(this);this.stop()};
g.h.kF=function(){this.Ea=null;this.tj&&!this.al&&(this.tj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Kua(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua(Jua,z6);S8=new Jua;g.h=A6.prototype;g.h.li=null;g.h.df=!1;g.h.tk=null;g.h.Ju=null;g.h.dk=null;g.h.uj=null;g.h.Pg=null;g.h.Ah=null;g.h.Ki=null;g.h.Mc=null;g.h.Lm=0;g.h.jf=null;g.h.bq=null;g.h.dh=null;g.h.dl=-1;g.h.EB=!0;g.h.Sh=!1;g.h.Hr=0;g.h.vp=null;var Pua={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.ZN=function(a){a=a.target;var b=this.vp;b&&3==R6(a)?b.nx():this.EC(a)};
g.h.EC=function(a){try{if(a==this.Mc)a:{var b=R6(this.Mc),c=this.Mc.C,d=this.Mc.getStatus();if(g.Od&&!g.sd(10)||g.Qd&&!g.rd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.dh&&!T6(this.Mc))break a;this.Sh||4!=b||7==c||(8==c||0>=d?this.o.bf(3):this.o.bf(2));K6(this);var e=this.Mc.getStatus();this.dl=e;var f=T6(this.Mc);(this.df=200==e)?(4==b&&G6(this),this.C?(Qua(this,b,f),g.dh&&this.df&&3==b&&(this.A.ka(this.u,"tick",this.UN),this.u.start())):F6(this,f),this.df&&!this.Sh&&(4==b?this.o.ip(this):(this.df=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.dh=3,E6(13)):(this.dh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Mc&&T6(this.Mc)}finally{}};
g.h.UN=function(){var a=R6(this.Mc),b=T6(this.Mc);this.Lm<b.length&&(K6(this),Qua(this,a,b),this.df&&4!=a&&C6(this))};
g.h.vN=function(a){J6((0,g.x)(this.uN,this,a),0)};
g.h.uN=function(a){this.Sh||(K6(this),F6(this,a),C6(this))};
g.h.KA=function(a){J6((0,g.x)(this.tN,this,a),0)};
g.h.tN=function(a){this.Sh||(G6(this),this.df=a,this.o.ip(this),this.o.bf(4))};
g.h.cancel=function(){this.Sh=!0;G6(this)};
g.h.DN=function(){this.tk=null;var a=(0,g.H)();0<=a-this.Ju?(2!=this.uj&&this.o.bf(3),G6(this),this.dh=2,E6(18),H6(this)):Tua(this,this.Ju-a)};
g.h.getLastError=function(){return this.dh};g.h=Wua.prototype;g.h.Fr=null;g.h.Wd=null;g.h.wp=!1;g.h.rx=null;g.h.On=null;g.h.qs=null;g.h.Gr=null;g.h.Ae=null;g.h.hg=-1;g.h.bl=null;g.h.Ck=null;g.h.connect=function(a){this.Gr=a;a=M6(this.o,null,this.Gr);E6(3);this.rx=(0,g.H)();var b=this.o.G;null!=b?(this.bl=b[0],(this.Ck=b[1])?(this.Ae=1,Xua(this)):(this.Ae=2,O6(this))):(a6(a,"MODE","init"),this.Wd=new A6(this,void 0,void 0,void 0),this.Wd.li=this.Fr,B6(this.Wd,a,!1,null,!0),this.Ae=0)};
g.h.fE=function(a){if(a)this.Ae=2,O6(this);else{E6(4);var b=this.o;b.sf=b.Tg.hg;$6(b,9)}a&&this.bf(2)};
g.h.Vq=function(a){return this.o.Vq(a)};
g.h.abort=function(){this.Wd&&(this.Wd.cancel(),this.Wd=null);this.hg=-1};
g.h.qx=function(){return!1};
g.h.EA=function(a,b){this.hg=a.dl;if(0==this.Ae)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.sf=this.hg;$6(c,2);return}this.bl=c[0];this.Ck=c[1]}else c=this.o,c.sf=this.hg,$6(c,2);else if(2==this.Ae)if(this.wp)E6(7),this.qs=(0,g.H)();else if("11111"==b){if(E6(6),this.wp=!0,this.On=(0,g.H)(),c=this.On-this.rx,!g.Od||g.sd(10)||500>c)this.hg=200,this.Wd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.On=this.qs=(0,g.H)(),this.wp=!1};
g.h.ip=function(){this.hg=this.Wd.dl;if(this.Wd.df)0==this.Ae?this.Ck?(this.Ae=1,Xua(this)):(this.Ae=2,O6(this)):2==this.Ae&&((!g.Od||g.sd(10)?!this.wp:200>this.qs-this.On)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.Ae?E6(9):2==this.Ae&&E6(10);var a=this.o;this.Wd.getLastError();a.sf=this.hg;$6(a,2)}};
g.h.ym=function(){return this.o.ym()};
g.h.isActive=function(){return this.o.isActive()};
g.h.bf=function(a){this.o.bf(a)};g.Ua(P6,g.Ne);var bva=/^https?$/i,Mwa=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.S?Lua(this.S):Lua(S8);this.O=this.S?this.S.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.AA,this);try{b6(S6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));ava(this,f);return}a=
c||"";var e=this.headers.clone();d&&g.tm(d,function(f,k){e.set(k,f)});
d=g.Za(e.Eb(),Zua);c=g.v.FormData&&a instanceof g.v.FormData;!g.bb(Mwa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{dva(this),0<this.F&&(this.P=Yua(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.P)),this.P?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.sx,this)):this.J=g.zf(this.sx,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),ava(this,f)}};
g.h.sx=function(){"undefined"!=typeof g.U1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Db.X.call(this)};
g.h.AA=function(){this.ga()||(this.aa||this.G||this.B?cva(this):this.sM())};
g.h.sM=function(){cva(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Pk=null;g.h.Qd=null;g.h.kc=null;g.h.Er=null;g.h.Rn=null;g.h.Nv=null;g.h.eo=null;g.h.Wl=0;g.h.NJ=0;g.h.yd=null;g.h.Xg=null;g.h.Qf=null;g.h.ai=null;g.h.Tg=null;g.h.Yp=null;g.h.Gj=-1;g.h.by=-1;g.h.sf=-1;g.h.nj=0;g.h.dj=0;g.h.Th=8;var a7=new g.Ne;g.Ua(fva,g.pe);g.Ua(gva,g.pe);g.Ua(hva,g.pe);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Er=b;this.Pk=c||{};d&&void 0!==e&&(this.Pk.OSID=d,this.Pk.OAID=e);this.C?(J6((0,g.x)(this.iw,this,a),100),lva(this)):this.iw(a)};
g.h.iw=function(a){this.Tg=new Wua(this);this.Tg.Fr=null;this.Tg.u=this.B;this.Tg.connect(a)};
g.h.qx=function(){return 0==this.o};
g.h.JA=function(a){this.Xg=null;ova(this,a)};
g.h.IA=function(){this.Qf=null;this.kc=new A6(this,this.w,"rpc",this.F);this.kc.li=null;this.kc.Hr=0;var a=this.Nv.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.w);Z5(a,"CI",this.Yp?"0":"1");Z5(a,"AID",this.Gj);V6(this,a);if(!g.Od||g.sd(10))Z5(a,"TYPE","xmlhttp"),B6(this.kc,a,!0,this.eo,!1);else{Z5(a,"TYPE","html");var b=this.kc,c=!!this.eo;b.uj=3;b.Pg=$5(a.clone());Sua(b,c)}};
g.h.EA=function(a,b){if(0!=this.o&&(this.kc==a||this.Qd==a))if(this.sf=a.dl,this.Qd==a&&3==this.o)if(7<this.Th){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Qf){if(this.kc)if(this.kc.dk+3E3<this.Qd.dk)X6(this),this.kc.cancel(),this.kc=null;else break a;Z6(this);E6(19)}}else this.by=c[1],0<this.by-this.Gj&&37500>c[2]&&this.Yp&&0==this.dj&&!this.ai&&(this.ai=J6((0,g.x)(this.oK,this),6E3));else $6(this,11)}else b!=Lwa.tQ.o&&$6(this,11);else if(this.kc==
a&&X6(this),!g.Lb(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Gj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.eo=e[2],e=e[3],null!=e?this.Th=e:this.Th=6,this.o=3,this.yd&&this.yd.cw(),this.Nv=M6(this,this.ym()?this.eo:null,this.Er),pva(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.yd&&this.yd.bw(e),this.dj=0)}}};
g.h.oK=function(){null!=this.ai&&(this.ai=null,this.kc.cancel(),this.kc=null,Z6(this),E6(20))};
g.h.ip=function(a){if(this.kc==a){X6(this);this.kc=null;var b=2}else if(this.Qd==a)this.Qd=null,b=1;else return;this.sf=a.dl;if(0!=this.o)if(a.df)1==b?(b=(0,g.H)()-a.dk,a7.dispatchEvent(new gva(a7,a.Ki?a.Ki.length:0,b,this.nj)),W6(this),this.A.length=0):pva(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.sf)){if(d=1==b)this.Qd||this.Xg||1==this.o||2<=this.nj?d=!1:(this.Xg=J6((0,g.x)(this.JA,this,a),qva(this,this.nj)),this.nj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.DE=function(a){if(!g.bb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.LO=function(a){a?E6(2):(E6(1),rva(this,8))};
g.h.Vq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Z=!1;return a};
g.h.isActive=function(){return!!this.yd&&this.yd.isActive(this)};
g.h.bf=function(a){a7.dispatchEvent(new hva(a7,a))};
g.h.ym=function(){return!(!g.Od||g.sd(10))};
g.h=sva.prototype;g.h.cw=function(){};
g.h.bw=function(){};
g.h.Zv=function(){};
g.h.Nq=function(){};
g.h.Mw=function(){return{}};
g.h.isActive=function(){return!0};g.h=tva.prototype;g.h.Qc=function(){return this.o.length+this.u.length};
g.h.isEmpty=function(){return g.cb(this.o)&&g.cb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.bb(this.o,a)||g.bb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.mpa)(b,a);0<=c?(g.eb(b,c),b=!0):b=!1;return b||g.fb(this.u,a)};
g.h.lc=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(b7,g.B);g.h=b7.prototype;g.h.mN=function(){this.Cd=Math.min(3E5,2*this.Cd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Cd+15E3*Math.random();g.cn(this.o,a);this.u=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Cd=5E3};g.Ua(c7,sva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.qh=function(a){return this.w.mi(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.ub||(this.ub=!0,g.ne(this.w),wva(this),g.ne(this.u),this.u=null)};
g.h.ga=function(){return this.ub};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.o;e&&(e.yd=null);d.yd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Gj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.A.extend(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&mva(this.o,c)};
g.h.cw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)mva(this.o,a[b])}this.R("handlerOpened")};
g.h.Zv=function(a){var b=2==a&&401==this.o.sf;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.Nq=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Mw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.A.extend(a,this.B);return a};
g.h.bw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),kva(this.o)):this.R("handlerMessage",new uva(a[0],a[1]))};
g.h.oO=function(){this.u.isActive();var a=this.o,b=0;a.kc&&b++;a.Qd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Eva=(0,g.H)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ua(m7,g.Q);m7.prototype.ke=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.JC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.ro(this.Ea),this.Ea=NaN)};
g.h.X=function(){this.stop();g.Q.prototype.X.call(this)};
g.h.JC=function(){this.Ea=NaN;this.o=g.bq(f7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.rP,this),onError:(0,g.x)(this.qP,this),Td:(0,g.x)(this.sP,this)})};
g.h.rP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.R("pairingComplete",new e6(c))};
g.h.qP=function(a){this.o=null;a.status&&404==a.status?this.u>=Nwa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=Nwa[this.u],this.Ea=g.po((0,g.x)(this.JC,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.sP=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var Nwa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.Zr("yt-remote-lounge-token-expiration")&&Iva(this);g.ro(this.u);this.u=g.po((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Fva(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||Iva(this)};
g.h.remove=function(a,b){var c=o7(this);Hva(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Wp=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.X=function(){g.ro(this.u);p7.Db.X.call(this)};
g.h.uF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.tF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Zr("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?u7(this):(this.A=(0,g.H)()+3E5,g.Yr("yt-remote-fast-check-period",this.A),this.Xt())};
g.h.isEmpty=function(){return g.A.isEmpty(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.A.filter(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.ro(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.X.call(this)};
g.h.Xt=function(){g.ro(this.w);this.w=NaN;this.u&&this.u.abort();var a=Lva(this);if(g.A.Qc(a)){var b=f7(this.B,"/pairing/get_screen_availability"),c={lounge_token:g.A.Eb(a).join(",")};this.u=g7(this.B,b,c,(0,g.x)(this.QM,this,a),(0,g.x)(this.PM,this))}else t7(this,{}),u7(this)};
g.h.QM=function(a,b){this.u=null;var c=g.A.Eb(Lva(this));if(g.tb(c,g.A.Eb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Rb("Changing Screen set during request."),this.Xt()};
g.h.PM=function(a){this.Rb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Rb=function(a){i7("OnlineScreenService",a)};g.Ua(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Wp=function(a,b,c,d){this.w.contains(a)?this.w.Wp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.ke=function(a){return a?this.o:g.ib(this.o,(0,g.be)(this.A,function(b){return!this.contains(b)},this))};
g.h.KC=function(){return(0,g.be)(this.ke(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.LC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.ne(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.ne(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.uP=function(a,b,c,d){g.bq(f7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Pva(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Pva(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Td:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.ne(this.w);g.ne(this.u);v7.Db.X.call(this)};
g.h.DF=function(){Qva(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ua(y7,g.Q);g.h=y7.prototype;g.h.kp=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.oe=function(a){this.ga()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.O,a)};
g.h.NC=function(){return null};
g.h.hu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.hu("");y7.Db.X.call(this)};g.Ua(A7,y7);g.h=A7.prototype;g.h.gu=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Sva(this)};
g.h.Hj=function(a){this.info("launchWithParams no-op for Cast: "+g.qk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.oe()},this),(0,g.x)(function(){this.oe(Error("Failed to stop receiver app."))},this)):this.oe(Error("Stopping cast device witout session."))};
g.h.hu=g.Ja;g.h.X=function(){this.info("disposeInternal");g.ro(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Db.X.call(this)};
g.h.LN=function(a,b){if(!this.ga())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.qk(c));switch(d){case "mdxSessionStatus":Rva(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.hx=function(a,b,c,d){Ova(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.po((0,g.x)(this.hx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.NC=function(){return this.o};
g.h.vP=function(a){this.ga()||a||(z7(this,"Cast session died."),this.oe())};g.Ua(B7,y7);g.h=B7.prototype;g.h.gu=function(a){this.A=a;this.A.addUpdateListener(this.P)};
g.h.Hj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.ro(this.C);this.A?this.A.stop((0,g.x)(this.oe,this,null),(0,g.x)(this.oe,this,"Failed to stop DIAL device.")):this.oe()};
g.h.X=function(){this.o();this.o=g.Ja;g.ro(this.C);this.A&&this.A.removeUpdateListener(this.P);this.A=null;B7.Db.X.call(this)};
g.h.yP=function(a){this.ga()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.oe())};
g.h.Pr=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Uva(this));a(b);Tva(this)}else this.F=(0,g.x)(function(){g.ro(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Uva(this));a(c);Tva(this)},this),this.C=g.po((0,g.x)(function(){this.F()},this),100)};
g.h.WF=function(a,b,c){Ova(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.kp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Pr(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Pr(b,c)},this))};g.Ua(C7,y7);C7.prototype.stop=function(){this.oe()};
C7.prototype.gu=g.Ja;C7.prototype.Hj=function(){g.ro(this.o);this.o=NaN;var a=k6(this.H.ke(),this.u.label);a?this.kp(a):this.oe(Error("No such screen"))};
C7.prototype.X=function(){g.ro(this.o);this.o=NaN;C7.Db.X.call(this)};g.Ua(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.xM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.GA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.MK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.A),Bva(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.MC,this)),this.w=Wva(this),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(k){this.Rb("Failed to set initial custom receivers: "+g.qk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Rb("Failed to initialize API: "+g.qk(k));
b(!1)},this))};
g.h.wO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.ke(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Vva(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ja,(0,g.x)(function(e){this.Rb("Failed to set initial custom receivers: "+g.qk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.hu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.xO=function(a){this.ga()?this.Rb("Setting connection data on disposed cast v2"):this.o?this.o.Hj(a):this.Rb("Setting connection data without a session")};
g.h.xP=function(){this.ga()?this.Rb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.GA,this),(0,g.x)(this.UM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.MC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=yva,b=g.w("yt.mdx.remote.debug.handlers_");g.fb(b||[],a);g.ne(this.o);D7.Db.X.call(this)};
g.h.Rb=function(a){i7("Controller",a)};
g.h.HA=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.tM=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Rb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Rb("Stopping receiver w/o session: "+a.friendlyName)}else this.Rb("onReceiverAction_ called without receiver.")};
g.h.MK=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Rb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Rb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Rb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.WF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Pr,b))};
g.h.GA=function(a){if(!this.ga()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Rb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.ke(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ne(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.HA,this,this.o)),this.o.Hj(null));this.o.gu(a)}}};
g.h.wP=function(){return this.o?this.o.NC():null};
g.h.UM=function(a){this.ga()||(this.Rb("Failed to estabilish a session: "+g.qk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.xM=function(a){E7("Receiver availability updated: "+a);if(!this.ga()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.MC=function(){this.ga()||(this.w=Wva(this),E7("Updating custom receivers: "+g.qk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(){this.Rb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.xO;D7.prototype.setConnectedScreenStatus=D7.prototype.wO;D7.prototype.stopSession=D7.prototype.xP;D7.prototype.getCastSession=D7.prototype.wP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.J=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.A=a.liveIngestionTime,this.w=
!isNaN(this.A))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.w?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Rb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Rb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Sa(this.setVolume,a,b))};
g.h.KB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.qk(b.style),g.A.extend(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Sa(this.KB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.qk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.IC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Sa(this.IC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Sa(this.nextVideo,a,b))};
g.h.rw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.rw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.X=function(){iwa(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.X.call(this)};
g.h.Mu=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.cb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.qM=function(a,b){this.R(a,b)};
g.h.uK=function(a){if(!a)this.Yl(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.Yl=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),jwa(this),this.R("remotePlayerChange")};
g.h.tK=function(a){a?(jwa(this),this.R("remotePlayerChange")):this.Yl(null)};
g.h.EK=function(){var a=fwa();a&&Y7(this,a)};
g.h.Rb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.qk(l));this.o.connect({method:"setPlaylist",
params:g.qk(l)},a,wua())}else g8("Connecting without params"),this.o.connect({},a,wua());lwa(this)};
g.h.dispose=function(){this.ga()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.ro(this.F);this.F=NaN;g.ro(this.G);this.G=NaN;this.w=null;g.dp(this.O);this.O.length=0;this.o.dispose();g.Q.prototype.X.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.mF=function(){this.kj(2)};
g.h.yK=function(){g8("Channel opened");this.P&&(this.P=!1,j8(this),this.J=g.po((0,g.x)(function(){g8("Timing out waiting for a screen.");this.kj(1)},this),15E3));
Aua(vva(this.o),this.S)};
g.h.vK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.wK=function(a){q6();isNaN(this.Vk())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.P=!0,g8("Channel error: "+a+" with reconnection in "+this.Vk()+" ms"),h8(this,2))};
g.h.xK=function(a){a.params?g8("Received: action="+a.action+", params="+g.qk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.ic)(a,function(c){return new d6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
owa(this,a);break;case "loungeScreenDisconnected":g.gb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
owa(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Za(this.u,function(c){return c.ob(b)})||iua(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.gb(this.u,function(c){return c.ob(b)});
break;case "gracefulDisconnect":break;case "playlistModified":qwa(this,a);break;case "nowPlaying":swa(this,a);break;case "onStateChange":rwa(this,a);break;case "onAdStateChange":twa(this,a);break;case "onVolumeChanged":uwa(this,a);break;case "onSubtitlesTrackChanged":pwa(this,a);break;case "nowAutoplaying":vwa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":wwa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.kO=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.bF=function(){var a=3;this.ga()||(a=0,isNaN(this.Vk())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.kj=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&q6();wva(this.o,a);this.dispose()};
g.h.aF=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.yO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.ro(this.F),this.F=g.po((0,g.x)(this.kO,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.qk(this.Sa.o)==g.qk(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.y)(c,function(d){this.R(d)},this)};
g.h.fx=function(){var a=this.o.C.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Vk=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.H)():NaN};
g.h.PE=function(){return this.A||"UNSUPPORTED"};
g.h.QE=function(){return this.C||""};
g.h.pP=function(){if(!isNaN(this.Vk())){var a=this.o.u;g.dn(a.o);a.start()}};
g.h.tO=function(a,b){l8(this,a,b);nwa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.qh;f8.prototype.getProxyState=f8.prototype.bF;f8.prototype.disconnect=f8.prototype.kj;f8.prototype.getPlayerContextData=f8.prototype.aF;f8.prototype.setPlayerContextData=f8.prototype.yO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.fx;f8.prototype.getReconnectTimeout=f8.prototype.Vk;f8.prototype.getAutoplayMode=f8.prototype.PE;f8.prototype.getAutoplayVideoId=f8.prototype.QE;f8.prototype.reconnect=f8.prototype.pP;
f8.prototype.sendMessage=f8.prototype.tO;g.r(m8,m7);g.h=m8.prototype;g.h.ke=function(a){return this.Bd.$_gs(a)};
g.h.contains=function(a){return!!this.Bd.$_c(a)};
g.h.get=function(a){return this.Bd.$_g(a)};
g.h.start=function(){this.Bd.$_st()};
g.h.add=function(a,b,c){this.Bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Bd.$_r(a,b,c)};
g.h.Wp=function(a,b,c,d){this.Bd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.Bd.$_ubk(this.u[a]);this.u.length=0;this.Bd=null;m7.prototype.X.call(this)};
g.h.tP=function(){this.R("screenChange")};
g.h.TL=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.uP;v7.prototype.$_gsppc=v7.prototype.LC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Wp;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.ke;v7.prototype.$_gos=v7.prototype.KC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.qh;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.B);g.h=G8.prototype;
g.h.X=function(){g.B.prototype.X.call(this);this.A.stop();this.C.stop();this.P.stop();this.U();this.o.unsubscribe("proxyStateChange",this.DA,this);this.o.unsubscribe("remotePlayerChange",this.hm,this);this.o.unsubscribe("remoteQueueChange",this.lp,this);this.o.unsubscribe("autoplayUpNext",this.bA,this);this.o.unsubscribe("previousNextChange",this.zA,this);this.o.unsubscribe("nowAutoplaying",this.vA,this);this.o.unsubscribe("autoplayDismissed",this.aA,this);this.o=this.B=null};
g.h.Xy=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.nx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.sK=function(a){this.P.iF(a)};
g.h.VO=function(a){this.Xy("control_subtitles_set_track",g.A.isEmpty(a)?null:a)};
g.h.VB=function(){var a=this.u.getOption("captions","track");g.A.isEmpty(a)||K8(this,a)};
g.h.nA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.hm,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.O.start();this.o.subscribe("remotePlayerChange",this.hm,this)}};
g.h.pL=function(){g.A.isEmpty(this.F)||Iwa(this,this.F);this.G=!1};
g.h.DA=function(a,b){this.C.stop();2==b&&this.UB()};
g.h.hm=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.oC(8));this.TB();break;case 1085:case 3:I8(this,new g.oC(9));break;case 1083:case 0:I8(this,new g.oC(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.oC(4));break;case 2:I8(this,new g.oC(4));H8(this,V7(a));
break;case -1:I8(this,new g.oC(64));break;case -1E3:I8(this,new g.oC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,Iwa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.O.isActive()||this.wC()}else Hwa(this)};
g.h.zA=function(){this.u.R("mdxpreviousnextchange")};
g.h.lp=function(){J8(this)||Hwa(this)};
g.h.eE=function(){this.o.rw()};
g.h.bA=function(){};
g.h.vA=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.aA=function(){this.u.R("mdxautoplaycanceled")};
g.h.bI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.wC=function(){if(J8(this)){var a=$7(this.o);this.w.Va(this.S);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.S=this.w.L(this.u,"onVolumeChange",this.nA)}};
g.h.TB=function(){this.A.stop();if(!this.o.ga()){var a=$7(this.o);1==a.playerState&&I8(this,new g.oC(8));H8(this,V7(a));this.A.start()}};
g.h.UB=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.S);M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.S);N8.prototype.A=function(a){Kwa(this,a.state)};g.r(O8,g.KN);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.vb(a,this.B,this),g.MN(this,(0,g.ic)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.Fe(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.Ze=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
O8.prototype.gd=function(a){g.KN.prototype.gd.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.ab()};g.r(P8,g.MK);g.h=P8.prototype;
g.h.create=function(){Bwa(g.Gy(this.player.N()));this.A.push(g.wo("yt-remote-before-disconnect",this.pK,this));this.A.push(g.wo("yt-remote-connection-change",this.yM,this));this.A.push(g.wo("yt-remote-receiver-availability-change",this.BA,this));this.A.push(g.wo("yt-remote-auto-connect",this.wM,this));this.A.push(g.wo("yt-remote-receiver-resumed",this.vM,this));this.A.push(g.wo("mdx-privacy-popup-confirm",this.XN,this));this.A.push(g.wo("mdx-privacy-popup-cancel",this.WN,this));this.BA()};
g.h.load=function(){this.player.cancelPlayback();g.MK.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Gwa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.O=a||0,this.player.R("progresssync",a,void 0));Jwa(this,this.F,this.F);g.hS(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.oe(this.B,this.o);this.o=this.B=null;g.MK.prototype.unload.call(this);g.hS(this.player.app,5);Q8(this)};
g.h.X=function(){g.xo(this.A);g.MK.prototype.X.call(this)};
g.h.Gl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Xy.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.dF=function(){return this.loaded?this.B.suggestion:null};
g.h.vy=function(){return this.o?$7(this.o).J:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.O};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.T(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Sc():!a.isAdPlaying()&&this.player.Sc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.xG=function(){this.o&&this.o.IC()};
g.h.pK=function(a){1==a&&(this.S=this.o?$7(this.o):null)};
g.h.yM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.S=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.ne(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.S)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.BA=function(){this.J=[this.u].concat(Dwa());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.PN=function(a){!this.P&&g.CC(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.wM=function(){var a=y8();R8(this,a)};
g.h.vM=function(){this.w=y8()};
g.h.XN=function(){this.P=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.WN=function(){this.P=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Oc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.yG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Jf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.aL.remote=P8;})(_yt_player);
